### PR TITLE
feat(add):add pull request template

### PR DESCRIPTION
**Pull request by pandora-1**

### CODE REVIEW

**Review by msyahrulsp — DISMISSED** [review]
LGTM

**Comment by gagaspbahar** [comment]
LGTM for me 2

**Review by gagaspbahar — DISMISSED** [review]

**Comment by gagaspbahar** [comment]
NOT APPROVED

**Review by gagaspbahar — APPROVED** [review]
ok

**Review by msyahrulsp — APPROVED** [review]
LGTM

**Pull request merged**
